%% Universidade Estadual de Londrina
%% Laboratory of Applied Biomechanics
%% Function created by Felipe Arruda Moura - 21/12/2022
%% The function generates a file with the x and y screen coordinates of the
%% .json generated by openpose. The sequence of the points is:

% ##{1,  "Nose"},
% ##{2,  "Neck"},
% ##{3,  "RShoulder"},
% ##{4,  "RElbow"},
% ##{5,  "RWrist"},
% ##{6,  "LShoulder"},
% ##{7,  "LElbow"},
% ##{8,  "LWrist"},
% ##{9,  "MidHip"},
% ##{10,  "RHip"},
% ##{11, "RKnee"},
% ##{12, "RAnkle"},
% ##{13, "LHip"},
% ##{14, "LKnee"},
% ##{15, "LAnkle"},
% ##{16, "REye"},
% ##{17, "LEye"},
% ##{18, "REar"},
% ##{19, "LEar"},
% ##{20, "LBigToe"},
% ##{21, "LSmallToe"},
% ##{22, "LHeel"},
% ##{23, "RBigToe"},
% ##{24, "RSmallToe"},
% ##{25, "RHeel"},

%% How to run:
%% example:
%% data=openposeread('directory_you_want')

function data=openposeread(diretorio)

pkg load io %(comment this line if you are running using Matlab puting a % in the begining of the line | Se você estiver rodando no Matlab, coloque o símbolo % no começo dessa linha)


D = diretorio;
S = dir(fullfile(D,'*json'));
N = numel(S);
C = cell(1,N);
M = nan(1,N);
for k = 1:N
fid = fopen(S(k).name);
raw = fread(fid,inf);
str = char(raw');
fclose(fid);
val = jsondecode(str);
dataframe = val.people(1).pose_keypoints_2d;
coordx=dataframe(1:3:end);
coordy=dataframe(2:3:end);
%data=[coordx coordy];
data(k,1:2:size(coordx,1)*2)=coordx';
data(k,2:2:size(coordx,1)*2)=coordy';

end
frames=[1:size(data,1)]';
data=[frames data];

end
